# Generated by Django 4.2.4 on 2023-08-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("qr_code_number", models.IntegerField(default=0)),
                ("full_name", models.CharField(max_length=50)),
                ("contact_number", models.CharField(max_length=12)),
                ("address", models.TextField()),
                ("mother_name", models.CharField(max_length=20)),
                ("mother_contact_number", models.CharField(max_length=12)),
                ("father_name", models.CharField(max_length=20)),
                ("father_contact_number", models.CharField(max_length=12)),
                ("wife_name", models.CharField(max_length=20)),
                ("wife_contact_number", models.CharField(max_length=12)),
                ("husband_name", models.CharField(max_length=20)),
                ("husband_contact_number", models.CharField(max_length=12)),
                ("education_institute", models.CharField(max_length=20)),
                ("education_institute_contact", models.CharField(max_length=12)),
                ("work_place_name", models.CharField(max_length=30)),
                ("work_place_address", models.TextField()),
                ("work_place_contact_number", models.CharField(max_length=12)),
                ("best_friend_name", models.CharField(max_length=20)),
                ("best_friend_contact_number", models.CharField(max_length=12)),
                ("qr_code", models.ImageField(blank=True, upload_to="documents/")),
            ],
        ),
    ]
