# Generated by Django 4.2.4 on 2023-08-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QrCodeGenerator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="email",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="password",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
