# Generated by Django 4.2.4 on 2023-08-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QrCodeGenerator", "0002_userinfo_email_userinfo_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="children_name",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="children_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="google_location_link",
            field=models.TextField(blank=True),
        ),
    ]
