# Generated by Django 4.2.4 on 2023-08-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "QrCodeGenerator",
            "0003_userinfo_children_name_userinfo_children_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="qr_code_number",
            field=models.TextField(unique=True),
        ),
    ]
