# Generated by Django 4.2.4 on 2023-08-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QrCodeGenerator", "0004_alter_userinfo_qr_code_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.TextField(blank=True),
        ),
    ]
