# Generated by Django 4.2.4 on 2023-08-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QrCodeGenerator", "0006_petownerinfo_travellerinfo_alter_userinfo_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="travellerinfo",
            name="destination_address",
            field=models.TextField(blank=True),
        ),
    ]
