# Generated by Django 4.2.4 on 2023-08-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QrCodeGenerator", "0007_travellerinfo_destination_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="petownerinfo",
            name="email",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name="petownerinfo",
            name="password",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="travellerinfo",
            name="email",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name="travellerinfo",
            name="password",
            field=models.TextField(blank=True),
        ),
    ]
