# Generated by Django 4.2.4 on 2023-08-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QrCodeGenerator", "0008_petownerinfo_email_petownerinfo_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalPic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image_name",
                    models.ImageField(blank=True, upload_to="documents/pet"),
                ),
            ],
        ),
    ]
