# Generated by Django 4.2.4 on 2023-08-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QrCodeGenerator", "0009_finalpic"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalpic",
            name="type_of_image",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
