# Generated by Django 4.2.4 on 2023-08-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QrCodeGenerator", "0010_finalpic_type_of_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalpic",
            name="date_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="finalpic",
            name="image_name",
            field=models.ImageField(blank=True, upload_to="documents/collage"),
        ),
    ]
