SALT = b"PZgBl75C9eKgFD-ABD4Ke_kuxci8bqTv1-cYrtKCj5E="
URL_PATH = "sarathiqrcodesolutions.pythonanywhere.com/get_qr_code_details/"
SENDER_MAIL_ID = "sarathiqrcodesolutions@gmail.com"
SUBJECT_FOR_FORGOT_PASSWORD = "YOUR NEW PASSWORD"
EMAIL_PASSWORD = "spesxyehvoseoeoa"
SMTP_URL = "smtp.gmail.com"
SMTP_PORT = 465
SUBJECT_ALERT_EMAIL = "Someone scan your QR code"
EMAIL_TYPE_FORGOT_PW = "forgot_password"
EMAIL_TYPE_INFO = "alert"
CONGRATULATION_MESSAGE = """<h1>Congratulations: <strong> {} </strong> your data have been saved successfully </h1>"""
